plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.voicevoxtts'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.voicevoxtts'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '0.0.2'

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
            excludes += ['**/x86_64/**']
        }
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'jp.hiroshiba.voicevoxcore:voicevoxcore-android:0.17.0'
}
